// Generated by meta.cpp

reflection::build_module("js_script")
	.cmp<&JSScriptModule::createScript, &JSScriptModule::destroyScript>("script", "JS Script / Script")
		.begin_array<&JSScriptModule::getScriptCount, &JSScriptModule::addScript, &JSScriptModule::removeScript>("scripts")
		.prop<&JSScriptModule::getScriptPath, &JSScriptModule::setScriptPath>("Path")
			.resourceAttribute(JSScript::TYPE)
		.blob_property<&JSScriptModule::getScriptData, &JSScriptModule::setScriptData>("Data")
		.end_array()
;

